/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.9.0. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input wire  clk // clock
    , input wire [31:0] a
    , input wire [31:0] b

      // Outputs
    , output wire [31:0] result
    );

  plusFloat plusFloat_inst
      (.clk (clk), .X (a), .Y (b), .R (result));
endmodule

