/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.9.0. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module VGAtopEntity
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire [11:0] sw

      // Outputs
    , output wire  hsync
    , output wire  vsync
    , output wire [11:0] rgb
    );
  // Test.hs:33:1-9
  reg  c$b_app_arg = 1'b0;
  wire [11:0] result_0;
  reg [11:0] c$app_arg = 12'b000000000000;
  // Test.hs:33:1-9
  wire  b;
  // Test.hs:33:1-9
  wire [23:0] ds;
  wire [13:0] result;

  // register begin
  always @(posedge clk ) begin : c$b_app_arg_register
    if ( rst) begin
      c$b_app_arg <= 1'b0;
    end else if (en) begin
      c$b_app_arg <= 1'b0;
    end
  end
  // register end

  assign result_0 = b ? sw : 12'b000000000000;

  // register begin
  always @(posedge clk ) begin : c$app_arg_register
    if ( rst) begin
      c$app_arg <= 12'b000000000000;
    end else if (en) begin
      c$app_arg <= result_0;
    end
  end
  // register end

  assign result = {ds[22:22],   ds[21:21],
                   c$app_arg};

  assign b = c$b_app_arg | (((ds[23:23])) == 1'b1);

  wire  video_on;
  wire  hsync_1;
  wire  vsync_1;
  wire  p_tick;
  wire [9:0] x;
  wire [9:0] y;
  vga_controller vga_controller_inst
    ( .clk_100MHz (clk)
    , .reset (rst)
    , .video_on (video_on)
    , .hsync (hsync_1)
    , .vsync (vsync_1)
    , .p_tick (p_tick)
    , .x (x)
    , .y (y) );

  assign ds = {video_on,   hsync_1,   vsync_1,
               p_tick,   x,   y};



  assign hsync = result[13:13];

  assign vsync = result[12:12];

  assign rgb = result[11:0];


endmodule

